services:
  provider:
    build:
      context: .
      dockerfile: provider/Dockerfile 
      args:
        DEVELOPMENT: 1
    volumes:
      - ./provider:/app
    ports:
      - '8000:8000'
    tty: true
  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile 
      args:
        DEVELOPMENT: 1
    environment:
      - PROVIDER_API_URL=http://provider:8000
    volumes:
      - ./consumer:/app
    ports:
      - '8001:8000'
    tty: true
